# -*- coding: utf-8 -*-
"""BioYeild_Digital_Twin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BmaHriMSV8du-EGgSSB4TZKII3EXoBe
"""

import numpy as np
import pandas as pd
from scipy.integrate import odeint
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

# Fix seed for reproducible results
np.random.seed(42)

# 1. Monod Model
def fermentation_model(y, t, mu_max, Ks, Y_xs, Y_px):
    X, S, P = y
    mu = mu_max * (S / (Ks + S)) if S > 0 else 0
    dXdt = mu * X
    dSdt = -(1 / Y_xs) * dXdt if S > 0 else 0
    dPdt = Y_px * dXdt if S > 0 else 0
    return [dXdt, dSdt, dPdt]

# 2. Generate 500 Batches
def generate_batch(batch_id):
    t = np.linspace(0, 24, 100)
    X0 = np.random.uniform(0.1, 0.5)
    S0 = np.random.uniform(20.0, 50.0)
    mu_max = np.random.uniform(0.3, 0.5)
    Ks = np.random.uniform(0.5, 1.5)
    Y_xs = np.random.uniform(0.4, 0.6)
    Y_px = np.random.uniform(0.1, 0.3)

    solution = odeint(fermentation_model, [X0, S0, 0], t, args=(mu_max, Ks, Y_xs, Y_px))
    df = pd.DataFrame(solution, columns=['Biomass_gL', 'Substrate_gL', 'Product_gL'])
    df['Time_hr'] = t
    df['Batch_ID'] = f"Batch_{batch_id}"
    df['DO_Percent'] = np.clip(100 - (df['Biomass_gL'] * 15) + np.random.normal(0, 2, len(t)), 5, 100)
    df['pH'] = 7.0 - (df['Biomass_gL'] * 0.1) + np.random.normal(0, 0.05, len(t))
    df['Y_px_true'] = Y_px  # True kinetic parameter
    return df

print("Generating 500 batches...")
all_batches = pd.concat([generate_batch(i) for i in range(1, 501)], ignore_index=True)

# 3. Feature Extraction
summary_list = []
for batch_id, group in all_batches.groupby('Batch_ID'):
    initial_S = group['Substrate_gL'].iloc[0]
    initial_X = group['Biomass_gL'].iloc[0]
    final_P = group['Product_gL'].iloc[-1]
    final_X = group['Biomass_gL'].iloc[-1]

    # Biomass produced & Growth kinetics
    delta_X = final_X - initial_X

    summary_list.append({
        'Initial_Substrate': initial_S,
        'Initial_Biomass': initial_X,
        'S0_X0_Ratio': initial_S / initial_X,
        'Delta_Biomass': delta_X,
        'Min_pH': group['pH'].min(),
        'DO_Stress_Hours': (group['DO_Percent'] < 20).sum() * (24 / 100),
        'Y_px_kinetic': group['Y_px_true'].iloc[0],
        'Final_Product_gL': final_P
    })

summary_df = pd.DataFrame(summary_list)

# 4. Train Model
X = summary_df[['Initial_Substrate', 'Initial_Biomass', 'S0_X0_Ratio',
               'Delta_Biomass', 'Min_pH', 'DO_Stress_Hours', 'Y_px_kinetic']]
y = summary_df['Final_Product_gL']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = GradientBoostingRegressor(n_estimators=200, learning_rate=0.08, random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
score = r2_score(y_test, predictions)
print(f"🚀 Final Model R² Score: {score:.3f}")

# 5. Plot Feature Importance
importances = pd.Series(model.feature_importances_, index=X.columns)
plt.figure(figsize=(8, 4))
importances.sort_values().plot(kind='barh', color='teal')
plt.title('Feature Importance for Fermentation Yield')
plt.xlabel('Importance Score')
plt.tight_layout()
plt.show()

import joblib

# Save the trained model to disk
joblib.dump(model, 'fermentation_model.pkl')

# Save feature column names
joblib.dump(list(X.columns), 'model_features.pkl')

print("✅ Model successfully exported as 'fermentation_model.pkl'!")