[supabase]
SUPABASE_URL = "https://uitlgejwclxrbhphlgha.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpdGxnZWp3Y2x4cmJocGhsZ2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyNDc5NjksImV4cCI6MjEwMjgyMzk2OX0.4EPFsK0ndYUUUmPeYjhaTOipz0CMI9MbnU2pYPlTXyE"
REDIRECT_URL = "http://localhost:8501"
